[kernel_config]
file = "/usr/src/linux/.config"
store = "kernel_config"
sudo = true

[dae_config]
file = "/etc/dae/config.dae"
store = "config.dae"
sudo = true
chmod = 644

[zshrc]
file = "~/.zshrc"
store = "zshrc"

[wayland_environment_im]
file = "~/.config/environment.d/im.conf"
store = "environment_im_wayland"

[portage_make_conf]
file = "/etc/portage/make.conf"
store = "portage_make.conf"
sudo = true

[portage_eselect_repo_conf]
file = "/etc/portage/repos.conf/eselect-repo.conf"
store = "portage_eselect_repo.conf"
sudo = true

[portage_world_file]
file = "/var/lib/portage/world"
store = "portage_world_file"
sudo = true
